export {
  CameroonLocations,
  getRegions,
  getDivisions,
  getSubdivisions,
  getDistricts,
  getRegionByCode,
  getDivisionByCode,
  getSubdivisionByCode,
  getDistrictByCode,
  getDivisionsInRegion,
  getSubdivisionsInDivision,
  getDistrictsInSubdivision,
  getSubdivisionsInRegion,
  getDistrictsInDivision,
  getDistrictsInRegion,
  getRegionOfDivision,
  getDivisionOfSubdivision,
  getSubdivisionOfDistrict,
  getDivisionOfDistrict,
  getRegionOfSubdivision,
  getRegionOfDistrict,
  region,
  division,
  subdivision,
  district,
  search,
  searchByType,
  RegionWrapper,
  DivisionWrapper,
  SubdivisionWrapper,
  DistrictWrapper,
  NotFoundError,
  CameroonLocationsError,
} from "./CameroonLocations";

export type {
  Region,
  Division,
  Subdivision,
  District,
  SearchResult,
  SearchType,
  CameroonDivisionsOptions,
} from "./types";

export { regions, divisions, subdivisions, districts } from "./data";
